from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "web" / "api-client.js"


CLIENT = r'''// Generated by scripts/generate_api_client.py. Do not edit by hand.
(() => {
  class APIError extends Error {
    constructor(error, status) {
      super(error?.message || `Request failed: ${status}`);
      this.name = "APIError";
      this.code = error?.code || "INTERNAL_ERROR";
      this.status = status;
      this.retryable = Boolean(error?.retryable);
      this.details = error?.details || {};
    }
  }

  class RoomAlignmentAPIClient {
    constructor(base = "/api/v1") { this.base = base; this.csrf = null; }

    async request(path, options = {}) {
      const headers = {"Accept": "application/json", ...(options.headers || {})};
      if (options.body !== undefined) headers["Content-Type"] = "application/json";
      if (options.method && options.method !== "GET" && this.csrf) headers["X-CSRF-Token"] = this.csrf;
      const response = await fetch(`${this.base}${path}`, {...options, headers, credentials: "same-origin"});
      const contentType = response.headers.get("Content-Type") || "";
      const payload = contentType.includes("json") ? await response.json() : await response.text();
      if (!response.ok) throw new APIError(payload?.error, response.status);
      return payload;
    }

    async session() { const value = await this.request("/session"); this.csrf = value.csrfToken; return value; }
    system() { return this.request("/system"); }
    grants() { return this.request("/grants"); }
    createGrant(value) { return this.request("/grants", {method: "POST", body: JSON.stringify(value)}); }
    revokeGrant(id) { return this.request(`/grants/${encodeURIComponent(id)}/revoke`, {method: "POST", body: "{}"}); }
    libraries() { return this.request("/libraries"); }
    createLibrary(value) { return this.request("/libraries", {method: "POST", body: JSON.stringify(value)}); }
    startScan(libraryId, value) { return this.request(`/libraries/${encodeURIComponent(libraryId)}/scans`, {method: "POST", body: JSON.stringify(value)}); }
    startClusterAnalysis(libraryId) { return this.request(`/libraries/${encodeURIComponent(libraryId)}/cluster-jobs`, {method: "POST", body: "{}"}); }
    clusterSuggestions(libraryId) { return this.request(`/libraries/${encodeURIComponent(libraryId)}/cluster-suggestions`); }
    scan(id) { return this.request(`/scans/${encodeURIComponent(id)}`); }
    cancelScan(id) { return this.request(`/scans/${encodeURIComponent(id)}/cancel`, {method: "POST", body: "{}"}); }
    media(libraryId, query = "") { return this.request(`/libraries/${encodeURIComponent(libraryId)}/media${query ? `?${query}` : ""}`); }
    mediaAsset(id) { return this.request(`/media/${encodeURIComponent(id)}`); }
    projects() { return this.request("/projects"); }
    project(id) { return this.request(`/projects/${encodeURIComponent(id)}`); }
    createProject(value) { return this.request("/projects", {method: "POST", body: JSON.stringify(value)}); }
    command(id, command, preview = false) { return this.request(`/projects/${encodeURIComponent(id)}/commands${preview ? "?preview=true" : ""}`, {method: "POST", body: JSON.stringify(command)}); }
    program(id) { return this.request(`/projects/${encodeURIComponent(id)}/program`); }
    programAt(id, outputUs) { return this.request(`/projects/${encodeURIComponent(id)}/program-at?outputUs=${encodeURIComponent(outputUs)}`); }
    suggestions(id) { return this.request(`/projects/${encodeURIComponent(id)}/suggestions`); }
    startAlignmentAnalysis(id) { return this.request(`/projects/${encodeURIComponent(id)}/alignment-jobs`, {method: "POST", body: "{}"}); }
    renderPlan(id, value) { return this.request(`/projects/${encodeURIComponent(id)}/render-plans`, {method: "POST", body: JSON.stringify(value)}); }
    attest(planId, warnings) { return this.request(`/render-plans/${encodeURIComponent(planId)}/review`, {method: "POST", body: JSON.stringify({acknowledgedWarnings: warnings})}); }
    render(planId, value) { return this.request(`/render-plans/${encodeURIComponent(planId)}/render`, {method: "POST", body: JSON.stringify(value)}); }
    job(id) { return this.request(`/jobs/${encodeURIComponent(id)}`); }
    cancelJob(id) { return this.request(`/jobs/${encodeURIComponent(id)}/cancel`, {method: "POST", body: "{}"}); }
    artifact(id) { return this.request(`/artifacts/${encodeURIComponent(id)}`); }
    manifest(id) { return this.request(`/artifacts/${encodeURIComponent(id)}/manifest`); }
    eventToken() { return this.request("/jobs/event-token", {method: "POST", body: "{}"}); }
  }

  window.RoomAlignmentAPI = {APIError, RoomAlignmentAPIClient};
})();
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != CLIENT:
            print(f"Generated client is stale: {TARGET}", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(CLIENT, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
